//! Typed emit helpers from Chronon Spectra schemas.
//!
//! Each type below is generated by a `spectra_schema!` / `spectra_metric!` invocation in
//! `schemas/`; the `*Logger` / `*Recorder` types are what [`SpectraTelemetrySink`](crate::SpectraTelemetrySink)
//! and [`crate::sink_forward`] call to emit a row or bump a counter/gauge.
//!
//! # Examples
//!
//! ```rust,no_run
//! use chronon_spectra_telemetry::helpers::ChrononRunsStartedRecorder;
//!
//! ChrononRunsStartedRecorder::record(
//!     1,
//!     serde_json::json!({"job_name": "nightly", "deployment_shape": "embedded"}),
//! );
//! ```

/// Row type and logger for the `chronon_executor_error` event table.
pub use crate::schemas::chronon_executor_error::{
    ChrononExecutorError, ChrononExecutorErrorLogger,
};
/// Recorder for the `chronon_partition_assignments` gauge.
pub use crate::schemas::chronon_partition_assignments::ChrononPartitionAssignmentsRecorder;
/// Recorder for the `chronon_remote_errors` counter.
pub use crate::schemas::chronon_remote_errors::ChrononRemoteErrorsRecorder;
/// Recorder for the `chronon_run_duration_ms` gauge.
pub use crate::schemas::chronon_run_duration_ms::ChrononRunDurationMsRecorder;
/// Row type and logger for the `chronon_run_log` event table.
pub use crate::schemas::chronon_run_log::{ChrononRunLog, ChrononRunLogLogger};
/// Recorder for the `chronon_runs_completed` counter.
pub use crate::schemas::chronon_runs_completed::ChrononRunsCompletedRecorder;
/// Recorder for the `chronon_runs_failed` counter.
pub use crate::schemas::chronon_runs_failed::ChrononRunsFailedRecorder;
/// Recorder for the `chronon_runs_started` counter.
pub use crate::schemas::chronon_runs_started::ChrononRunsStartedRecorder;
/// Row type and logger for the `chronon_scheduler_log` event table.
pub use crate::schemas::chronon_scheduler_log::{ChrononSchedulerLog, ChrononSchedulerLogLogger};
/// Recorder for the `chronon_scheduler_ticks` counter.
pub use crate::schemas::chronon_scheduler_ticks::ChrononSchedulerTicksRecorder;
